Repository jupyterlite/ai, pull requests merged in 2025-06, with the labels that each got.

#87 Handle compatibility with chromeAI and WebLLM
  src/default-providers/ChromeAI/instructions.ts
  src/default-providers/WebLLM/instructions.ts
  src/default-providers/index.ts
  src/provider.ts
  src/settings/panel.tsx
  src/tokens.ts
  style/base.css
Labels: enhancement

#88 Export the IAIProviderRegistry token
  src/index.ts
Labels: bug

#89 Add a welcome message
  package.json
  src/chat-handler.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#92 Chat panel tweaks
  src/index.ts
  style/base.css
Labels: enhancement

#94 Fix the messages datetime
  src/chat-handler.ts
Labels: bug

#96 System prompt configurable
  schema/chat.json
  schema/system-prompts.json
  scripts/settings-checker.js
  src/base-completer.ts
  src/chat-handler.ts
  src/default-prompts.ts
  src/default-providers/Anthropic/completer.ts
  src/default-providers/ChromeAI/completer.ts
  src/default-providers/ChromeAI/settings-schema.json
  src/default-providers/MistralAI/completer.ts
  src/default-providers/Ollama/completer.ts
  src/default-providers/OpenAI/completer.ts
  src/default-providers/WebLLM/completer.ts
  src/index.ts
  src/provider.ts
  src/settings/index.ts
  src/settings/textarea.tsx
  src/tokens.ts
  style/base.css
Labels: enhancement

#97 Add UI tests
  .github/workflows/tests.yml
  .gitignore
  schema/provider-registry.json
  src/settings/panel.tsx
  ui-tests/README.md
  ui-tests/jupyter_server_test_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/chat-panel.spec.ts
  ui-tests/tests/chat-panel.spec.ts-snapshots/chat-icon-linux.png
  ui-tests/tests/code-completion.spec.ts
  ui-tests/tests/test-utils.ts
  ui-tests/yarn.lock
Labels: maintenance

#101 Open the settings from the chat panel
  src/chat-handler.ts
  style/base.css
Labels: enhancement
