Repository jupyterlite/ai, pull requests merged in 2025-09, with the labels that each got.

#148 More cleanup
  schema/plugin.json
  src/completion/completion-provider.ts
  src/components/token-usage-display.tsx
  src/components/tool-select.tsx
  src/icons.ts
  src/index.ts
  src/models/settings-model.ts
  src/tokens.ts
  src/widgets/ai-settings.tsx
  src/widgets/chat-wrapper.tsx
  style/ai-settings.css
  style/base.css
  style/index.css
Labels: maintenance

#150 Bump dependencies, disable tracing for now
  package.json
  src/agent.ts
  yarn.lock
Labels: maintenance

#153 Add `jupyterlab-cell-diff`
  pyproject.toml
Labels: feature

#162 Call the diff command directly when setting the cell content
  src/agent.ts
  src/index.ts
  src/tools/notebook.ts
Labels: enhancement

#159 Add the secrets manager
  package.json
  schema/settings-model.json
  src/agent.ts
  src/completion/completion-provider.ts
  src/index.ts
  src/models/settings-model.ts
  src/tokens.ts
  src/widgets/ai-settings.tsx
  src/widgets/provider-config-dialog.tsx
  yarn.lock
Labels: enhancement

#168 Bump @jupyter/chat to 0.18.1
  package.json
  yarn.lock
Labels: bug
