Repository jupyterlite/ai, pull requests merged in 2025-01, with the labels that each got.

#14 Dynamic settings for providers
  .gitignore
  README.md
  package.json
  pyproject.toml
  schema/ai-provider.json
  scripts/settings-generator.js
  src/index.ts
  src/llm-models/utils.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#26 Update README.md
  README.md
  img/2-jupyterlab-settings.png
Labels: documentation

#22 Anthropic (Claude) provider
  README.md
  package.json
  schema/ai-provider.json
  scripts/settings-generator.js
  src/completion-provider.ts
  src/llm-models/anthropic-completer.ts
  src/llm-models/base-completer.ts
  src/llm-models/utils.ts
  yarn.lock
Labels: enhancement

#30 Upgrade the jupyterlite-core package in deployment
  .github/workflows/deploy.yml
Labels: bug, maintenance

#32 Fix installation of pre-released jupyterlite in deployment
  .github/workflows/deploy.yml
Labels: maintenance

#33 Deployment with prereleased jupyterlite-pyodide-kernel
  .github/workflows/deploy.yml
Labels: maintenance
