Repository jupyterlite/ai, pull requests merged in 2025-05, with the labels that each got.

#68 Fix the API keys in provider when using the secrets manager
  src/provider.ts
  src/settings/panel.tsx
  src/settings/settings-connector.ts
Labels: bug

#70 Fix completer settings
  src/base-completer.ts
  src/default-providers/Anthropic/completer.ts
  src/default-providers/ChromeAI/completer.ts
  src/default-providers/MistralAI/completer.ts
  src/default-providers/OpenAI/completer.ts
  src/provider.ts
Labels: bug

#73 Better handling of default values in settings
  src/settings/panel.tsx
Labels: enhancement

#69 Add Ollama provider
  package.json
  scripts/settings-checker.js
  src/default-providers/Ollama/completer.ts
  src/default-providers/Ollama/instructions.ts
  src/default-providers/Ollama/settings-schema.json
  src/default-providers/index.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#76 Update `@langchain/community` to fix ChromeAI
  package.json
  yarn.lock
Labels: bug

#47 WebLLM
  package.json
  scripts/settings-checker.js
  src/default-providers/WebLLM/completer.ts
  src/default-providers/WebLLM/instructions.ts
  src/default-providers/WebLLM/settings-schema.json
  src/default-providers/index.ts
  src/provider.ts
  src/types/service-worker.d.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#75 Upgrade secrets manager
  package.json
  schema/provider-registry.json
  src/index.ts
  src/settings/panel.tsx
  yarn.lock
Labels: enhancement

#79 Install `ipywidgets` for the demo deployed on GitHub Pages
  .github/workflows/deploy.yml
Labels: maintenance

#81 Remove the custom settings connector
  package.json
  src/index.ts
  src/settings/index.ts
  src/settings/panel.tsx
  src/settings/settings-connector.ts
Labels: enhancement

#86 Pin PyPI version of jupyter-secrets-manager
  pyproject.toml
Labels: maintenance
